rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - build(8) except for gapic-generator-java
      - build(8) for gapic-generator-java
      - build (11)
      - build (17)
      - cla/google
      - compatibility
      - graalvm-presubmit-sdk-platform-java-a (java-graalvm-ci-prod)
      - graalvm-presubmit-sdk-platform-java-b (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-a-downstream-kms
        (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-b-downstream-kms
        (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-a-downstream-kmsinventory
        (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-b-downstream-kmsinventory
        (java-graalvm-ci-prod)
      - library_generation
      - library-generation-integration-test (java-hermetic-build-prod)
      - library-generation-lint-python
      - library-generation-lint-shell
      - library-generation-unit-tests
      - lint
      - should-run-library-generation-tests
      - showcase (11)
      - showcase (17)
  - pattern: bump-minor-v-for-LTS
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - build(8) except for gapic-generator-java
      - build(8) for gapic-generator-java
      - build (11)
      - build (17)
      - cla/google
      - compatibility
      - graalvm-presubmit-sdk-platform-java-a (java-graalvm-ci-prod)
      - graalvm-presubmit-sdk-platform-java-b (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-a-downstream-kms
        (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-b-downstream-kms
        (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-a-downstream-kmsinventory
        (java-graalvm-ci-prod)
      - >-
        graalvm-presubmit-sdk-platform-java-b-downstream-kmsinventory
        (java-graalvm-ci-prod)
      - library_generation
      - library-generation-integration-test (java-hermetic-build-prod)
      - library-generation-lint-python
      - library-generation-lint-shell
      - library-generation-unit-tests
      - lint
      - should-run-library-generation-tests
      - showcase (11)
      - showcase (17)
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-java
    permission: push
