gapic_generator_version: 2.41.1-SNAPSHOT # {x-version-update:gapic-generator-java:current}
googleapis_commitish: 573205a81b9b96ea6d4e0365373839b59f4b427e
# the libraries are ordered with respect to library name, which is
# java-{library.library_name} or java-{library.api-shortname} when
# library.library_name is not defined.
libraries:
- api_shortname: common-protos
  name_pretty: Common Protos
  product_documentation: https://github.com/googleapis/api-common-protos
  api_description: Protobuf classes for Google's common protos.
  release_level: stable
  client_documentation: https://cloud.google.com/java/docs/reference/proto-google-common-protos/latest/history
  distribution_name: com.google.api.grpc:proto-google-common-protos
  excluded_dependencies: "proto-google-common-protos,grpc-google-common-protos,proto-google-common-protos-parent"
  excluded_poms: "proto-google-common-protos-bom,proto-google-common-protos"
  library_type: OTHER
  GAPICs:
  - proto_path: google/api
  - proto_path: google/apps/card/v1
  - proto_path: google/cloud
  - proto_path: google/cloud/audit
  - proto_path: google/cloud/location
  - proto_path: google/geo/type
  - proto_path: google/logging/type
  - proto_path: google/longrunning
  - proto_path: google/rpc
  - proto_path: google/rpc/context
  - proto_path: google/shopping/type
  - proto_path: google/type
- api_shortname: iam
  name_pretty: IAM
  product_documentation: https://cloud.google.com/iam
  api_description: Manages access control for Google Cloud Platform resources
  release_level: stable
  client_documentation: https://cloud.google.com/java/docs/reference/proto-google-iam-v1/latest/overview
  distribution_name: com.google.api.grpc:proto-google-iam-v1
  excluded_dependencies: "grpc-google-iam-v1"
  excluded_poms: "proto-google-iam-v1-bom,google-iam-policy,proto-google-iam-v1"
  library_type: OTHER
  GAPICs:
  - proto_path: google/iam/v1
  - proto_path: google/iam/v2
  - proto_path: google/iam/v2beta
