version: 2.1

# ======================= JOBS =======================
jobs:
  gapic-generator-java-tests:
    docker:
      - image: l.gcr.io/google/bazel
    working_directory: /home/circleci/project/gapic-generator-java
    steps:
      - checkout
      - run:
          name: Build targets
          command: |
            bazel build //...
      - run:
          name: Test targets
          command: |
            bazel test //...
      - store_test_results:
          path:  ~/.cache/bazel
  google-java-format:
    docker:
      - image: l.gcr.io/google/bazel
    working_directory: /home/circleci/workspace/gapic-generator-java
    steps:
      - checkout
      - run:
          name: Java Linter
          command: |
            bazel build //:google_java_format_verification
  license-header:
    docker:
      - image: circleci/golang:1.13
    working_directory: /home/circleci/workspace/gapic-generator-java
    steps:
      - checkout
      - run:
          name: License Header
          command: |
            go get -u github.com/google/addlicense
            addlicense -c "Google LLC" -l apache -check $(find $PWD -type f -name '*.java')
# ======================= WORKFLOWS =======================

workflows:
  version: 2
  run_tests:
    jobs:
      - gapic-generator-java-tests
      - google-java-format
      - license-header
